#!/usr/bin/env python3
"""Generate the fleet schema-slug baseline that gate-106 checks against.

The baseline records WHICH APP DECLARES WHICH SLUG today. It is deliberately
descriptive, not prescriptive: it takes no view on who *should* own a generic
word, so generating it needs no product decision and no fleet meeting. Gate-106
uses it for one question only, which is "is this app newly claiming a slug that
today belongs to someone else".

Regenerate after a deliberate, agreed ownership change:

    python3 build_fleet_schema_slugs.py <app-dir> [<app-dir> ...] \
        > ../../contracts/fleet-schema-slugs.json

Take CANONICAL checkouts only. A workspace usually holds scratch clones of the
same app beside it, and those carry the same <id>; scanning a parent directory
would fold a stale clone's slugs into the baseline as if they still shipped.

A slug is read from every OpenAPI-shaped descriptor an app ships under
lib/Settings (any filename: the fleet uses *_register.json, register.d
fragments and others), matching how RegisterDescriptorService discovers them.
"""
import json
import os
import re
import sys
import glob
import collections


def descriptors(app_dir):
    """Every OpenAPI-shaped descriptor an app ships under lib/Settings."""
    roots = [os.path.join(app_dir, "lib", "Settings")]
    for root in list(roots):
        roots.append(os.path.join(root, "register.d"))
    for root in roots:
        for path in sorted(glob.glob(os.path.join(root, "*.json"))):
            try:
                with open(path, encoding="utf-8") as handle:
                    data = json.load(handle)
            except Exception:
                continue
            if isinstance(data, dict) and isinstance(data.get("components"), dict):
                yield path, data



def declared_slug(key, entry):
    """The slug this entry CLAIMS, or None when it only extends one.

    A register.d fragment addresses an existing schema by its dict KEY and
    carries no `slug`: larpinq's mcp-adoption fragment adds `configuration`
    to the schema keyed `skill`, whose slug is `larping_skill`. Reading the
    key as a claim there invents a cross-app collision out of a fragment that
    declares nothing.

    A full declaration is recognised by carrying schema BODY (`properties` or
    `title`). Only then does an absent `slug` fall back to the key, which is
    what OpenRegister does when it derives a slug for a schema that ships
    without one.
    """
    slug = entry.get("slug")
    if isinstance(slug, str) and slug:
        return slug
    if "properties" in entry or "title" in entry:
        return key
    return None


def app_id(app_dir):
    """The app's declared <id>, which is the only authority on its name."""
    info = os.path.join(app_dir, "appinfo", "info.xml")
    try:
        with open(info, encoding="utf-8") as handle:
            match = re.search(r"<id>([^<]+)</id>", handle.read())
    except OSError:
        return None
    return match.group(1).strip() if match else None


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: build_fleet_schema_slugs.py <app-dir> [<app-dir> ...]")

    owners = collections.defaultdict(set)
    scanned = []
    for app_dir in sys.argv[1:]:
        if not os.path.isdir(app_dir):
            sys.exit(f"not a directory: {app_dir}")
        app = app_id(app_dir)
        if app is None:
            continue
        found = False
        for _path, data in descriptors(app_dir):
            # A descriptor may name an app other than the directory it sits in
            # (an integration register shipped alongside), and the declaring
            # app owns the slug, not the directory.
            meta = (data.get("x-openregister") or {})
            # A mock register is demo data. RegisterDescriptorService skips it
            # in the inventory for the same reason: a slug that only a mock
            # declares is not the app laying claim to the word.
            if meta.get("type") == "mock":
                continue
            declaring = (meta.get("app") or app)
            schemas = (data.get("components") or {}).get("schemas") or {}
            for key, value in schemas.items():
                if not isinstance(value, dict):
                    continue
                slug = declared_slug(key, value)
                if slug is not None:
                    owners[slug.lower()].add(declaring)
                    found = True
        if found:
            scanned.append(app)

    payload = {
        "$comment": (
            "Generated by build_fleet_schema_slugs.py. Descriptive, not prescriptive: "
            "it records who declares each slug TODAY so gate-106 can refuse a NEW "
            "cross-app claim. It does not say who should own a word."
        ),
        "version": 1,
        "apps_scanned": sorted(scanned),
        "owners": {slug: sorted(apps) for slug, apps in sorted(owners.items())},
    }
    json.dump(payload, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
