#!/usr/bin/env python3
"""Gate 106: an app must not newly claim a schema slug another app owns.

WHY THIS GATE EXISTS

A schema slug is GLOBAL on a shared OpenRegister. `SchemaMapper::find()`
matches on `LOWER(slug)` across every application and returns the first row it
fetches, and register descriptors write relations as a bare `"$ref": "Person"`
rather than a qualified path. Two apps that pick the same word therefore
resolve to each other, and the failure is silent: the wrong schema answers, or
an import binds to a foreign row.

Measured on the dev instance 2026-08-31: 20 slugs were claimed by more than one
app across the fleet's shipped registers, and 35 duplicated slugs coexisted
live. `application` alone meant a built app, a job application and a school
admission in three different apps, with 4 percent property overlap.

WHAT IT CHECKS, AND WHAT IT DELIBERATELY DOES NOT

It checks ONE thing: is this app declaring a slug that, in the recorded fleet
baseline, belongs only to other apps.

It takes NO view on who *should* own a generic word. That is a product
decision, it is not mechanical, and a gate that guessed would be wrong in both
directions. So the baseline is descriptive: it records who declares what today.
The 29 slugs that already have several claimants stay green for every app
already listed, because reddening existing state teaches people to ignore the
gate. Only a NEW claim fails.

The gate cannot see sibling apps at run time: CI checks out one repository. The
baseline in contracts/fleet-schema-slugs.json is what makes a cross-app answer
possible from a single-repo checkout, and it is regenerated by
build_fleet_schema_slugs.py when ownership deliberately changes.

Exit codes: 0 pass, 1 findings, 2 usage/wiring.
"""
import argparse
import glob
import json
import os
import re
import sys


CONTRACT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "contracts", "fleet-schema-slugs.json"
)


def declared_slug(key, entry):
    """The slug this entry CLAIMS, or None when it only extends one.

    Mirrors build_fleet_schema_slugs.py exactly: a register.d fragment
    addresses an existing schema by its dict KEY and carries no `slug`, so
    reading the key as a claim would invent a collision out of a fragment that
    declares nothing.
    """
    slug = entry.get("slug")
    if isinstance(slug, str) and slug:
        return slug
    if "properties" in entry or "title" in entry:
        return key
    return None


def app_id(app_dir):
    """The app's declared <id>, the only authority on its name."""
    try:
        with open(os.path.join(app_dir, "appinfo", "info.xml"), encoding="utf-8") as handle:
            match = re.search(r"<id>([^<]+)</id>", handle.read())
    except OSError:
        return None
    return match.group(1).strip() if match else None


def descriptor_files(app_dir):
    """Every descriptor path an app ships under lib/Settings."""
    found = []
    for root in (
        os.path.join(app_dir, "lib", "Settings"),
        os.path.join(app_dir, "lib", "Settings", "register.d"),
    ):
        found.extend(sorted(glob.glob(os.path.join(root, "*.json"))))
    return found


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("app_dir", nargs="?", default=".")
    parser.add_argument("--changed-file", action="append", default=[],
                        help="Restrict to these descriptors (ADR-020 diff scoping).")
    parser.add_argument("--contract", default=CONTRACT)
    args = parser.parse_args()

    app = app_id(args.app_dir)
    if app is None:
        print("no appinfo/info.xml <id> — nothing to attribute a slug to")
        print("checked 0 descriptor(s): 0 finding(s)")
        return 0

    try:
        with open(args.contract, encoding="utf-8") as handle:
            owners = json.load(handle)["owners"]
    except Exception as exc:
        print(f"[cross-app-schema-slug] contract unreadable: {exc}", file=sys.stderr)
        return 2

    paths = descriptor_files(args.app_dir)
    if args.changed_file:
        wanted = {os.path.normpath(p) for p in args.changed_file}
        paths = [p for p in paths
                 if os.path.normpath(os.path.relpath(p, args.app_dir)) in wanted]

    findings = 0
    checked = 0
    for path in paths:
        try:
            with open(path, encoding="utf-8") as handle:
                data = json.load(handle)
        except Exception:
            continue
        if not isinstance(data, dict) or not isinstance(data.get("components"), dict):
            continue
        meta = data.get("x-openregister") or {}
        if meta.get("type") == "mock":
            continue
        declaring = meta.get("app") or app
        schemas = (data.get("components") or {}).get("schemas") or {}
        checked += 1
        for key, entry in schemas.items():
            if not isinstance(entry, dict):
                continue
            slug = declared_slug(key, entry)
            if slug is None:
                continue
            holders = owners.get(slug.lower())
            if not holders or declaring in holders:
                continue
            findings += 1
            rel = os.path.relpath(path, args.app_dir)
            print(
                f"FAIL {rel}: app '{declaring}' declares schema slug '{slug}', which belongs to "
                f"{', '.join(repr(h) for h in holders)}. Slugs are GLOBAL on a shared "
                f"OpenRegister, so both definitions resolve to each other and the wrong one can "
                f"answer. Pick a slug that says which of the two this is (the fleet's convention "
                f"is a qualifier, as in 'job-application' or 'larping_skill'), or, if this really "
                f"is the same entity, consume the owning app's schema instead of redeclaring it. "
                f"If ownership genuinely moved, regenerate "
                f"contracts/fleet-schema-slugs.json in the same PR."
            )

    print(f"checked {checked} descriptor(s): {findings} finding(s)")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
