// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'WayOfWork/way-of-work',
    {
      type: 'category',
      label: 'Working at Conduction',
      collapsed: false,
      items: [
        'WayOfWork/onboarding',
        'WayOfWork/organisation',
        'WayOfWork/code-of-conduct',
        'WayOfWork/vacancies',
      ],
    },
    {
      type: 'category',
      label: 'Building Software',
      collapsed: false,
      items: [
        'WayOfWork/spec-driven-development',
        'WayOfWork/development-pipeline',
        'WayOfWork/way-of-working',
        'WayOfWork/contributing',
        'WayOfWork/release-process',
      ],
    },
    {
      type: 'category',
      label: 'Support & Safety',
      collapsed: false,
      items: [
        'WayOfWork/customer-support',
        'iso/iso-intro',
        'iso/incident-reporting',
        'iso/security',
        'iso/quality-policy',
        'iso/security-policy',
        'iso/privacy-policy',
      ],
    },

    {
      type: 'category',
      label: 'Hydra',
      collapsed: false,
      link: { type: 'doc', id: 'hydra/README' },
      items: [
        {
          type: 'category',
          label: 'Pipeline',
          collapsed: true,
          items: [
            'hydra/pipeline-overview',
            'hydra/agentic-workflow',
            'hydra/agent-configuration',
            'hydra/container-architecture',
            'hydra/deployment-models',
            'hydra/github-workflow',
            'hydra/context',
          ],
        },
        {
          type: 'category',
          label: 'Operations',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'hydra/operations' }],
        },
        {
          type: 'category',
          label: 'Retrospectives',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'hydra/retrospectives' }],
        },
      ],
    },

    {
      type: 'category',
      label: 'Using Claude',
      collapsed: false,
      link: { type: 'doc', id: 'claude/README' },
      items: [
        'claude/getting-started',
        'claude/walkthrough',
        'claude/agents',
        'claude/rad-platform',

        {
          type: 'category',
          label: 'Setup',
          collapsed: true,
          items: [
            'claude/workstation-setup',
            'claude/global-claude-settings',
            'claude/docker',
            'claude/playwright-setup',
            'claude/local-llm',
          ],
        },
        {
          type: 'category',
          label: 'Workflow',
          collapsed: true,
          items: [
            'claude/workflow',
            'claude/app-lifecycle',
            'claude/commands',
            'claude/commands-openspec',
            'claude/commands-tender',
          ],
        },
        {
          type: 'category',
          label: 'Writing',
          collapsed: true,
          items: [
            'claude/writing-specs',
            'claude/writing-adrs',
            'claude/writing-skills',
            'claude/writing-docs',
            'claude/skill-checklist',
            'claude/skill-patterns',
            'claude/skill-evals',
          ],
        },
        {
          type: 'category',
          label: 'Quality & testing',
          collapsed: true,
          items: [
            'claude/testing',
            'claude/parallel-agents',
            'claude/frontend-standards',
          ],
        },

        'claude/retrofit',
      ],
    },

    'WayOfWork/about-this-manual',
  ],
};

module.exports = sidebars;
