// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'WayOfWork/way-of-work',
    {
      type: 'category',
      label: 'Working at Conduction',
      collapsed: false,
      items: [
        'WayOfWork/onboarding',
        'WayOfWork/organisation',
        'WayOfWork/code-of-conduct',
        'WayOfWork/vacancies',
      ],
    },
    {
      type: 'category',
      label: 'Building Software',
      collapsed: false,
      items: [
        'WayOfWork/spec-driven-development',
        'WayOfWork/development-pipeline',
        'WayOfWork/way-of-working',
        'WayOfWork/contributing',
        'WayOfWork/release-process',
      ],
    },
    {
      type: 'category',
      label: 'Support & Safety',
      collapsed: false,
      items: [
        'WayOfWork/customer-support',
        'iso/iso-intro',
        'iso/incident-reporting',
        'iso/security',
        'iso/quality-policy',
        'iso/security-policy',
        'iso/privacy-policy',
      ],
    },
    {
      type: 'category',
      label: 'Claude workflow',
      items: [{ type: 'autogenerated', dirName: 'claude' }],
    },
    'WayOfWork/about-this-manual',
  ],
};

module.exports = sidebars;
